Repository AlexTelon/FlexiCharge-Backend, pull requests merged in 2023-09, with the labels that each got.

#178 Hotfix/#173 move env secrets to gh secrets
  .github/workflows/backend-CI.yml
Labels: security

#176 Pull request template #174
  .github/pull_request_template.md
Labels: enhancement

#199 Update backend-CI.yml to include dev
  .github/workflows/backend-CI.yml
Labels: enhancement

#203 Move secrets to environment variables
  .github/workflows/backend-CI.yml
  backend-app/.env.example
  backend-app/src/config/index.js
  backend-app/src/config/validations.js
  backend-app/src/data-access-layer/db.js
  backend-app/src/data-access-layer/klarna-repository.js
  backend-app/src/presentation-layer/middleware/auth.middleware.js
  backend-app/src/presentation-layer/middleware/jwt.middleware.js
Labels: security

#206 Feature/#205 add mock data for starting a transaction
  backend-app/docs/openapi.yaml
  backend-app/src/presentation-layer/charge-point-router-api.js
  backend-app/src/presentation-layer/chargers-router-api.js
  backend-app/src/presentation-layer/reservations-router-api.js
  backend-app/src/presentation-layer/transactions-router-api.js
Labels: documentation, HTTP, OCPP
